# controller-gen
OutputDir=D:/xxliang/JavaProgram/xxliang-yunc/yunc-service/yunc-service-media/src/main/java

# mapper.xml-gen
OutputDirXml=D:/xxliang/JavaProgram/xxliang-yunc/yunc-service/yunc-service-media/src/main/resources/mapper

# pojo -gen
OutputDirBase=D:/xxliang/JavaProgram/xxliang-yunc/yunc-pojo/yunc-pojo-media/src/main/java


#  author
author=xxliang
# package
parent=com.xxliang.yunc

# datasource
jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://127.0.0.1:13306/ymcc-media?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
jdbc.user=root
jdbc.pwd=123456