# ?????????
OutputDir=D:/xxliang/JavaProgram/xxliang-yunc/yunc-pojo/yunc-pojo-system/src/main/java

# mapper.xml???????
OutputDirXml=D:/xxliang/JavaProgram/xxliang-yunc/yunc-pojo/yunc-pojo-system/src/main/resources/mapper

# pojo query ???????
OutputDirBase=D:/xxliang/JavaProgram/xxliang-yunc/yunc-pojo/yunc-pojo-system/src/main/java


#  ??
author=xxliang
# ??
parent=com.xxliang.yunc

# ?????
jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://127.0.0.1:13306/ymcc-system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
jdbc.user=root
jdbc.pwd=123456